using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using DbMetaTool.Infrastructure;
using Xunit;

namespace DbMetaTool.Tests;

public class ParseCreateTableColumnsTests
{
    [Fact]
    public void ParsesColumnsAndSkipsConstraintBlocks()
    {
        var updater = new FirebirdUpdater();
        var parsed = InvokeParseCreateTableColumns(
            updater,
            """
            CREATE TABLE TEST_TABLE (
                ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                NAME VARCHAR(100) NOT NULL,
                UNIQUE (NAME),
                CONSTRAINT PK_TEST_TABLE PRIMARY KEY (ID)
            );
            """);

        var columnNames = GetColumnNames(parsed);

        Assert.Equal(new[] { "ID", "NAME" }, columnNames);
        Assert.Empty(GetParseWarnings(updater));
    }

    [Fact]
    public void SkipsComputedFragmentsAndLogsMalformedItems()
    {
        var updater = new FirebirdUpdater();
        var parsed = InvokeParseCreateTableColumns(
            updater,
            """
            CREATE TABLE CALCULATED_DATA (
                ID INTEGER NOT NULL,
                COMPUTED BY (ID + 1),
                BROKEN_FRAGMENT,
                VALUE VARCHAR(20),
                PRIMARY KEY (ID)
            );
            """);

        var columnNames = GetColumnNames(parsed);
        var failures = GetParseWarnings(updater);

        Assert.Equal(new[] { "ID", "VALUE" }, columnNames);
        Assert.Single(failures);
        Assert.Contains("BROKEN_FRAGMENT", failures[0].Error, System.StringComparison.OrdinalIgnoreCase);
    }

    private static object InvokeParseCreateTableColumns(FirebirdUpdater updater, string sql)
    {
        var domainDefinitionType = typeof(FirebirdUpdater).GetNestedType("DomainDefinition", BindingFlags.NonPublic)!;
        var domainDictionaryType = typeof(Dictionary<,>).MakeGenericType(typeof(string), domainDefinitionType);
        var emptyDomains = Activator.CreateInstance(domainDictionaryType);

        var method = typeof(FirebirdUpdater).GetMethod(
            "ParseCreateTableColumns",
            BindingFlags.Instance | BindingFlags.NonPublic);

        return method!.Invoke(updater, new[] { sql, emptyDomains!, null })!;
    }

    private static List<string> GetColumnNames(object parsedTableDefinition)
    {
        var columns = (IEnumerable)GetPropertyValue(parsedTableDefinition, "Columns");
        var columnNames = new List<string>();

        foreach (var column in columns)
        {
            columnNames.Add((string)GetPropertyValue(column!, "ColumnName"));
        }

        return columnNames;
    }

    private static List<(string File, string Error)> GetParseWarnings(FirebirdUpdater updater)
    {
        var field = typeof(FirebirdUpdater).GetField("_parseWarnings", BindingFlags.Instance | BindingFlags.NonPublic)!;
        var failureItems = (IEnumerable)field.GetValue(updater)!;
        var results = new List<(string File, string Error)>();

        foreach (var failure in failureItems)
        {
            var file = (string)failure!.GetType().GetField("Item1")!.GetValue(failure)!;
            var error = (string)failure.GetType().GetField("Item2")!.GetValue(failure)!;
            results.Add((file, error));
        }

        return results;
    }

    private static object GetPropertyValue(object instance, string propertyName)
    {
        var property = instance.GetType().GetProperty(
            propertyName,
            BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);

        return property!.GetValue(instance)!;
    }
}
