CREATE OR ALTER PROCEDURE "PRC_RETURN_BOOK"
(
  "P_LOAN_ID" "D_ID",
  "P_BOOK_ID" "D_ID"
)
AS
BEGIN
  UPDATE "LOAN"
     SET "CLOSED_AT" = CURRENT_TIMESTAMP,
         "STATE" = 'CLOSED'
   WHERE "ID" = :P_LOAN_ID
     AND "BOOK_ID" = :P_BOOK_ID
     AND "CLOSED_AT" IS NULL;

  UPDATE "BOOK"
     SET "STATE" = 'AVAILABLE'
   WHERE "ID" = :P_BOOK_ID;
END
