CREATE OR ALTER PROCEDURE "PRC_BORROW_BOOK"
(
  "P_LOAN_ID" "D_ID",
  "P_BOOK_ID" "D_ID",
  "P_MEMBER_ID" "D_ID",
  "P_DUE_AT" TIMESTAMP
)
AS
BEGIN
  INSERT INTO "LOAN" ("ID", "BOOK_ID", "MEMBER_ID", "LOANED_AT", "DUE_AT", "STATE")
  VALUES (:P_LOAN_ID, :P_BOOK_ID, :P_MEMBER_ID, CURRENT_TIMESTAMP, :P_DUE_AT, 'OPEN');

  UPDATE "BOOK"
     SET "STATE" = 'ON_LOAN'
   WHERE "ID" = :P_BOOK_ID;
END
