CREATE OR ALTER PROCEDURE "PRC_REGISTER_MEMBER"
(
  "P_ID" "D_ID",
  "P_FULL_NAME" "D_NAME",
  "P_EMAIL" "D_EMAIL",
  "P_PHONE" VARCHAR(30)
)
AS
BEGIN
  INSERT INTO "MEMBER" ("ID", "FULL_NAME", "EMAIL", "STATE", "PHONE", "REGISTERED_AT")
  VALUES (:P_ID, :P_FULL_NAME, :P_EMAIL, 'ACTIVE', :P_PHONE, CURRENT_TIMESTAMP);
END
