CREATE OR ALTER PROCEDURE "PRC_FULFILL_HOLD"
(
  "P_HOLD_ID" "D_ID",
  "P_LOAN_ID" "D_ID",
  "P_DUE_AT" TIMESTAMP
)
AS
BEGIN
  INSERT INTO "LOAN" ("ID", "BOOK_ID", "MEMBER_ID", "LOANED_AT", "DUE_AT", "STATE")
  SELECT :P_LOAN_ID, "BOOK_ID", "MEMBER_ID", CURRENT_TIMESTAMP, :P_DUE_AT, 'OPEN'
    FROM "HOLD"
   WHERE "ID" = :P_HOLD_ID;

  DELETE FROM "HOLD"
   WHERE "ID" = :P_HOLD_ID;

  UPDATE "BOOK"
     SET "STATE" = 'ON_LOAN'
   WHERE "ID" = (SELECT "BOOK_ID" FROM "LOAN" WHERE "ID" = :P_LOAN_ID);
END
